%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    D:\Alex_Liberzon\womersley_profile_fit-master\code\test\data.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2020/09/06 10:26:25

%% Import the data
[~, ~, raw] = xlsread('test\data.xlsx','Sheet1','A2:AE249');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[4,8,12,16,20]);
raw = raw(:,[1,2,3,5,6,7,9,10,11,13,14,15,17,18,19,21,22,23,24,25,26,27,28,29,30,31]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Normalisedtime1 = data(:,1);
PA_Surgery_90_Aortic1 = data(:,2);
PA_Surgery_90_Branch1 = data(:,3);


Normalisedtime2 = data(:,4);
PA_Surgery_135_Aortic = data(:,5);
PA_Surgery_135_Branch = data(:,6);

Normalisedtime3 = data(:,7);
PA_Hybrid_90_Aortic = data(:,8);
PA_Hybrid_90_Branch = data(:,9);


Normalisedtime4 = data(:,10);
PA_Hybrid_115_Aortic = data(:,11);
PA_Hybrid_115_Branch = data(:,12);

Normalisedtime5 = data(:,13);
PA_Hybrid_135_Aortic = data(:,14);
PA_Hybrid_135_Branch = data(:,15);

Normalisedtime6 = data(:,16);
PA_Chimney_90_Aortic = data(:,17);
PA_Chimney_90_Branch = data(:,18);

Normalisedtime7 = data(:,20);
PA_Chimney_115_Aortic = data(:,21);
PA_Chimney_115_Branch = data(:,22);

Normalisedtime8 = data(:,24);
PA_Chimney_135_Aortic = data(:,25);
PA_Chimney_135_Branch = data(:,26);

%% Clear temporary variables
clearvars data raw cellVectors R;